name: Vote Servers

on:
  schedule:
    # 5:00 WIB
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci --omit dev

      - name: Run script
        env:
          NODE_ENV: "production"
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FALLBACK_TOKENS: ${{ secrets.FALLBACK_TOKENS }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: npm start
